server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: test1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      #      create : ??(???????) table? ?? drop? ???(???? ?????????) - ?????????
      #      update : ???? ????? alter? ??. ????? ??. -??????
      #      validate : ??DB?? ???? check? ?? ddl? ??X(??? ????? ??) - ??????
      ddl-auto: create
    #      ???? ddl, dml?? ??? ???? ???? ??
    show_sql: true

